CrateType:
  Block:
    OpenChest:
      chest-open-duration: 60
      early-reward-hologram: true
      reward-hologram-delay: 0
      reward-holo-attach-to-item: true
      early-open-actions: false
    OpenChestRolling:
      chest-open-duration: 60
      early-reward-hologram: true
      reward-hologram-delay: 0
      reward-holo-attach-to-item: true
      early-open-actions: false
  Inventory:
    Roulette:
      inv-name: '&8&l> &6&l%crate%'
      tick-sound: BLOCK_IRON_DOOR_CLOSE, 5, 5
      tile-update-ticks: 2
      tick-speed-per-run: 3
      final-crate-tick-length: 11
      random-blocks:
        - BLACK_STAINED_GLASS_PANE
        - WHITE_STAINED_GLASS_PANE
        - GRAY_STAINED_GLASS_PANE
    CSGO:
      inv-name: '&8&l> &6&l%crate%'
      tick-sound: BLOCK_CHEST_LOCKED, 5, 5
      identifier-block: REDSTONE_TORCH_ON;0
      tick-speed-per-run: 3
      final-crate-tick-length: 11
      tile-update-ticks: 2
      close-speed: 3
      filler-blocks:
        - BLACK_STAINED_GLASS_PANE
        - WHITE_STAINED_GLASS_PANE
        - GRAY_STAINED_GLASS_PANE
    Menu:
      inv-name: '&8&l> &6&l%crate%'
      inventory-rows: 3
      minimum-rewards: 1
      maximum-rewards: 8
    Enclose:
      inv-name: '&8&l> &6&l%crate%'
      tick-sound: ENTITY_PLAYER_LEVELUP, 5, 5
      fill-block: STAINED_GLASS_PANE;2
      reward-amount: 1
      update-speed: 2
      inventory-rows: 2
    Discover:
      inv-name: '&8&l> &6&l%crate%'
      tick-sound: ENTITY_ITEM_PICKUP, 3, 10
      click-sound: BLOCK_TRIPWIRE_CLICK_ON, 5, 5
      uncover-sound: ENTITY_PLAYER_LEVELUP, 5, 5
      inventory-rows: 3
      minimum-rewards: 1
      maximum-rewards: 4
      count: true
      random-display-duration: 50
      cover-block: CHEST;0
      cover-block-name: '&aReward #%number%'
      cover-block-lore: '&7You have &f%remaining-clicks% rewards to chose from.'
      reward-block: LIME_STAINED_GLASS
      reward-block-name: "&aReward"
      reward-block-waiting-name: '&aUncover all rewards to unlock'
      reward-block-unlock-name: '&aClick me to unlock your reward.'

      
